version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.prod
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
