version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9091:8080"   # Host 9090 -> container 8080

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
        - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
        - backend