FROM eclipse-temurin:17-jdk-alpine

RUN mkdir /opt/app
WORKDIR /opt/app

# Copy your Spring Boot jar
COPY target/DailyVerse-0.0.1-SNAPSHOT.jar /opt/app/app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar", "--spring.config.location=application.properties"]
