# Use Maven to build the app
FROM maven:3.9.3-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Then use a smaller JDK image for runtime
FROM eclipse-temurin:17-jre
WORKDIR /opt/app
COPY --from=build /app/target/DailyVerse-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
